name: 			Eduardo Diaz Sancha's Site
markdown: 		kramdown
highlighter:  rouge
baseurl:		/
source:      	.
destination: 	./_site
url: 			http://edsancha.com
paginate: 5
paginate_path: "/blog/:num"
plugins:
  - jekyll-gist
  - jekyll-paginate
head-scripts:
  - /js/progress-bar.js
